# Generated by Django 2.2.7 on 2019-11-30 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterInventory',
            fields=[
                ('mi_inventoryid', models.AutoField(primary_key=True, serialize=False)),
                ('mi_partname', models.CharField(max_length=100)),
                ('mi_numberofstocks', models.IntegerField()),
                ('mi_parlevel', models.IntegerField()),
            ],
            options={
                'db_table': 'tblMasterInventory',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('s_supplierid', models.AutoField(primary_key=True, serialize=False)),
                ('s_suppliername', models.CharField(max_length=30)),
                ('s_companyname', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('s_contractstartdate', models.DateTimeField()),
                ('s_is_active', models.BooleanField(default=True)),
                ('s_phone', models.CharField(max_length=16)),
                ('s_email', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tblSupplier',
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('si_supplierinvoiceid', models.AutoField(primary_key=True, serialize=False)),
                ('si_supplierinvoicenumber', models.CharField(max_length=16)),
                ('si_date', models.DateTimeField()),
                ('si_hst', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
            options={
                'db_table': 'tblSupplierInvoice',
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('so_supplierordernumber', models.AutoField(primary_key=True, serialize=False)),
                ('so_date', models.DateTimeField(auto_now_add=True)),
                ('so_supplierid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.Supplier')),
            ],
            options={
                'db_table': 'tblSupplierOrder',
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soli_quantity', models.IntegerField()),
                ('soli_inventoryid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.MasterInventory')),
                ('soli_supplierordernumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.SupplierOrder')),
            ],
            options={
                'db_table': 'jncSupplierOrderLineItem',
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sili_quantityshipped', models.IntegerField(default=0)),
                ('sili_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sili_inventoryid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.MasterInventory')),
                ('sili_supplierinvoicenumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.SupplierInvoice')),
            ],
            options={
                'db_table': 'jncSupplierInvoiceLineItem',
            },
        ),
    ]
