# Generated by Django 2.2.7 on 2019-11-30 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('masterInventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('d_defectid', models.AutoField(primary_key=True, serialize=False)),
                ('d_quantity', models.IntegerField(default=0)),
                ('d_date', models.DateTimeField(auto_now_add=True)),
                ('d_defectdesc', models.CharField(default='', max_length=200)),
                ('d_employeeid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Employee')),
                ('d_supplierordernumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.SupplierOrder')),
            ],
            options={
                'db_table': 'tblDefect',
            },
        ),
    ]
