# Generated by Django 2.2.6 on 2019-12-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterInventory', '0002_defect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='d_defectdesc',
        ),
    ]
