# Generated by Django 2.2.6 on 2019-12-03 20:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterInventory', '0003_remove_defect_d_defectdesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierinvoicelineitem',
            name='sili_inventoryid',
        ),
        migrations.RemoveField(
            model_name='supplierinvoicelineitem',
            name='sili_supplierinvoicenumber',
        ),
        migrations.AddField(
            model_name='masterinventory',
            name='mi_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='so_isreceived',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Defect',
        ),
        migrations.DeleteModel(
            name='SupplierInvoice',
        ),
        migrations.DeleteModel(
            name='SupplierInvoiceLineItem',
        ),
    ]
