# Generated by Django 2.2.6 on 2019-12-03 20:25

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191130_1805'),
        ('masterInventory', '0004_auto_20191203_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('si_supplierinvoiceid', models.AutoField(primary_key=True, serialize=False)),
                ('si_supplierinvoicenumber', models.CharField(max_length=16)),
                ('si_date', models.DateTimeField()),
                ('si_hst', models.DecimalField(decimal_places=2, default=Decimal('0.13'), max_digits=3)),
                ('si_ordernumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.SupplierOrder')),
            ],
            options={
                'db_table': 'tblSupplierInvoice',
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sili_quantityshipped', models.IntegerField(default=0)),
                ('sili_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sili_inventoryid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.MasterInventory')),
                ('sili_supplierinvoicenumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.SupplierInvoice')),
            ],
            options={
                'db_table': 'jncSupplierInvoiceLineItem',
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('d_defectid', models.AutoField(primary_key=True, serialize=False)),
                ('d_quantity', models.IntegerField(default=0)),
                ('d_date', models.DateTimeField(auto_now_add=True)),
                ('d_defectdesc', models.CharField(default='', max_length=200)),
                ('d_employeeid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Employee')),
                ('d_inventoryid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.MasterInventory')),
                ('d_supplierinvoicenumber', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masterInventory.SupplierInvoice')),
            ],
            options={
                'db_table': 'tblDefect',
            },
        ),
    ]
