# Generated by Django 2.2.7 on 2019-11-30 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterInventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('mt_modeltypeid', models.AutoField(primary_key=True, serialize=False)),
                ('mt_modeltypename', models.CharField(max_length=100)),
                ('mt_isactive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tblkModelType',
            },
        ),
        migrations.CreateModel(
            name='PartInventory',
            fields=[
                ('pi_partid', models.AutoField(primary_key=True, serialize=False)),
                ('pi_isactive', models.BooleanField(default=True)),
                ('pi_inventoryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterInventory.MasterInventory')),
            ],
            options={
                'db_table': 'jncPartInventory',
            },
        ),
        migrations.CreateModel(
            name='SubassemblyInventory',
            fields=[
                ('si_subassemblyid', models.AutoField(primary_key=True, serialize=False)),
                ('si_inventoryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='masterInventory.MasterInventory')),
            ],
            options={
                'db_table': 'jncSubassemblyInventory',
            },
        ),
        migrations.CreateModel(
            name='BikeModel',
            fields=[
                ('bm_modelid', models.AutoField(primary_key=True, serialize=False)),
                ('bm_modelname', models.CharField(max_length=100)),
                ('bm_thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('bm_isactive', models.BooleanField(default=True)),
                ('bm_modeltype', models.ForeignKey(on_delete=models.SET('Discontinued'), to='bike.ModelType')),
            ],
            options={
                'db_table': 'tblModel',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('b_bikeid', models.AutoField(primary_key=True, serialize=False)),
                ('b_modelid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.BikeModel')),
            ],
            options={
                'db_table': 'tblBike',
            },
        ),
        migrations.CreateModel(
            name='SubassemblyPartsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spl_quantity', models.IntegerField()),
                ('spl_isactive', models.BooleanField(default=True)),
                ('spl_partid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.PartInventory')),
                ('spl_subassemblyid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.SubassemblyInventory')),
            ],
            options={
                'db_table': 'tblSubassemblyPartsList',
                'unique_together': {('spl_subassemblyid', 'spl_partid')},
            },
        ),
        migrations.CreateModel(
            name='Subassembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_quantity', models.IntegerField()),
                ('s_isactive', models.BooleanField(default=True)),
                ('s_modelid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.BikeModel')),
                ('s_subassemblyid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.SubassemblyInventory')),
            ],
            options={
                'db_table': 'jncModelSubassembly',
                'unique_together': {('s_modelid', 's_subassemblyid')},
            },
        ),
        migrations.CreateModel(
            name='PartList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pl_quantity', models.IntegerField(default=0)),
                ('pl_modelid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.BikeModel')),
                ('pl_partid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bike.PartInventory')),
            ],
            options={
                'db_table': 'tblPartList',
                'unique_together': {('pl_modelid', 'pl_partid')},
            },
        ),
    ]
