# Generated by Django 2.2.7 on 2019-11-30 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BikeStatus',
            fields=[
                ('bs_bikestatusid', models.AutoField(primary_key=True, serialize=False)),
                ('bs_bikestatus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tblkBikeStatus',
            },
        ),
        migrations.AddField(
            model_name='bike',
            name='b_bikestatusid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bike.BikeStatus'),
        ),
    ]
