# Generated by Django 2.2.7 on 2019-11-30 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_bikemodel_bm_modelprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='b_modelid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike.BikeModel'),
        ),
        migrations.AlterField(
            model_name='partinventory',
            name='pi_inventoryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterInventory.MasterInventory'),
        ),
        migrations.AlterField(
            model_name='partlist',
            name='pl_modelid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike.BikeModel'),
        ),
        migrations.AlterField(
            model_name='partlist',
            name='pl_partid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike.PartInventory'),
        ),
        migrations.AlterField(
            model_name='subassembly',
            name='s_modelid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike.BikeModel'),
        ),
        migrations.AlterField(
            model_name='subassemblyinventory',
            name='si_inventoryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='masterInventory.MasterInventory'),
        ),
        migrations.AlterField(
            model_name='subassemblypartslist',
            name='spl_partid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike.PartInventory'),
        ),
        migrations.AlterField(
            model_name='subassemblypartslist',
            name='spl_subassemblyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike.SubassemblyInventory'),
        ),
    ]
