# Generated by Django 2.2.7 on 2019-11-30 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_userid', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('e_streetaddress1', models.CharField(max_length=100)),
                ('e_streetaddress2', models.CharField(blank=True, max_length=100)),
                ('e_city', models.CharField(max_length=100)),
                ('e_province', models.CharField(max_length=100)),
                ('e_postalcode', models.CharField(max_length=6)),
                ('e_country', models.CharField(default='CA', max_length=100)),
                ('e_phonenumber', models.CharField(max_length=15)),
                ('e_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('e_startdate', models.DateTimeField(auto_now_add=True)),
                ('e_sinnumber', models.CharField(max_length=9)),
                ('e_isapprentice', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tblEmployee',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('c_customerid', models.AutoField(primary_key=True, serialize=False)),
                ('c_streetaddress1', models.CharField(max_length=100)),
                ('c_streetaddress2', models.CharField(blank=True, max_length=100)),
                ('c_city', models.CharField(max_length=100)),
                ('c_province', models.CharField(max_length=100)),
                ('c_postalcode', models.CharField(max_length=6)),
                ('c_country', models.CharField(default='CA', max_length=100)),
                ('c_phonenumber', models.CharField(max_length=15)),
                ('c_dateregistered', models.DateTimeField(auto_now_add=True)),
                ('c_issubscribed', models.BooleanField(default=True)),
                ('c_companyname', models.CharField(blank=True, max_length=150)),
                ('c_isactive', models.BooleanField(default=True)),
                ('c_userid', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tblCustomer',
            },
        ),
    ]
