# Generated by Django 2.2.7 on 2019-11-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_startdate',
            field=models.DateField(),
        ),
    ]
