# Generated by Django 2.2.7 on 2019-12-01 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191130_1805'),
        ('taskschedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='s_employeeid',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='s_endtime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='s_starttime',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='s_taskid',
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_starttime', models.TimeField()),
                ('es_endtime', models.TimeField()),
                ('es_employeeid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Employee')),
                ('es_scheduleid', models.ManyToManyField(to='taskschedule.Schedule')),
                ('es_taskid', models.ManyToManyField(to='taskschedule.Task')),
            ],
            options={
                'db_table': 'jncSchedule',
            },
        ),
    ]
