# Generated by Django 2.2.7 on 2019-11-30 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bike', '0002_auto_20191130_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInvoice',
            fields=[
                ('ci_invoiceid', models.AutoField(primary_key=True, serialize=False)),
                ('ci_date', models.DateTimeField(auto_now_add=True)),
                ('ci_hst', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ci_subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ci_shippingfee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ci_isactive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tblCustomerInvoice',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('co_customeroderid', models.AutoField(primary_key=True, serialize=False)),
                ('co_paymentmethod', models.CharField(max_length=50)),
                ('co_corderdate', models.DateTimeField(auto_now_add=True)),
                ('co_customerid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Customer')),
            ],
            options={
                'db_table': 'tblCustomerOrder',
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coli_quantity', models.IntegerField()),
                ('coli_isactive', models.BooleanField(default=True)),
                ('coli_bikeid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike.Bike')),
                ('coli_customeroderid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.CustomerOrder')),
            ],
            options={
                'db_table': 'jncCustomerOrderLineItem',
            },
        ),
        migrations.CreateModel(
            name='CustomerInvoiceLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cili_quantityordered', models.IntegerField()),
                ('cili_quantityshipped', models.IntegerField()),
                ('cili_isactive', models.BooleanField(default=True)),
                ('cili_bikeid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bike.Bike')),
                ('cili_invoiceid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.CustomerInvoice')),
            ],
            options={
                'db_table': 'jncCustomerInvoieLineItem',
            },
        ),
        migrations.AddField(
            model_name='customerinvoice',
            name='ci_customeroderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.CustomerOrder'),
        ),
    ]
